version: 2

sources:
  - name: raw
    schema: gz_raw_data
    description: greenweez raw data source
    tables:
      - name: sales
        identifier: raw_gz_sales
        description: sales of greenweez / we have one row per products_id found in each orders_id.
        tests:
          - unique:
              column_name: "(pdt_id || '-' || orders_id)"
        columns:
          - name: date_date
            description: the date of purchase
        freshness: 
          warn_after:
            count: 90
            period: day
        loaded_at_field: "CAST(date_date as TIMESTAMP)"
      - name: product
        identifier: raw_gz_product
        description: products of greenweez
        columns:
          - name: products_id
            description: Primary key of the table
            tests:
              - unique
              - not_null
      - name: ship
        identifier: raw_gz_ship
        description: shipping information of greenweez
        columns:
          - name: orders_id
            description: Primary key of the table
            tests:
              - unique
              - not_null
models:
  - name: int_sales_margin
    description: join on sales and products
    tests:
      - unique:
          column_name: "(products_id || '-' || orders_id)"
      - not_null:
          column_name:
            - products_id
            - orders_id
            - margin
            - revenue
            - date_date
            - purchase_cost
            - quantity
  - name: int_orders_margin
    description: margin calculation on orders
    columns:
      - name: orders_id
        description: primary key
        data_type: INT64
        tests:
          - unique
          - not_null
      - name: date_date
        description: date of the purchase
        data_type: DATE
      - name: revenue
        description: sum of revenues from the order
        data_type: FLOAT64
      - name: quantity
        description: sum of quantity of products in the order
        data_type: FLOAT64
      - name: purchase_cost
        description: quantity * purchase price
        data_type: FLOAT64
      - name: margin
        description: revenue - purchase cost
        data_type: FLOAT64
